### PR TITLE
add new task: Curry's paradox

### PR DESCRIPTION
**Pull request by juvi21**
A paradox in logic and semantics that uses self-reference to seemingly prove any arbitrary statement.

### CODE REVIEW

**Comment by teknium1** [comment]
> A paradox in logic and semantics that uses self-reference to seemingly prove any arbitrary statement.

Hello! we have updated the structure of the repo. Would you be able to update your branch to conform? Then can merge, thank you!

**Comment by juvi21** [comment]
I'm not sure about the math markdown notation when we are using these `codeblocks`. I guess it should be fine but correct me.

**Comment by teknium1** [comment]
> I'm not sure about the math markdown notation when we are using these `codeblocks`. I guess it should be fine but correct me.

We can make exceptions where the current schema doesn't work for a task/examples. If you want to update that let me know, otherwise I can merge. Thanks!

**Comment by juvi21** [comment]
I think it would be good to make a slight exception in this case. I've reformatted things, and it's now ready to merge from my side.

**Comment by teknium1** [comment]
Merged!

**Pull request merged**
