### PR TITLE
Stack based reasoning

### PR DESCRIPTION
**Pull request by bigattichouse**
Noticed that thinking in terms of a stack (FILO buffer) is very difficult for most models. I believe it's a good test of reasoning ability to think of how the information will be processed after it's handed off to another party.

### CODE REVIEW

**Comment by teknium1** [comment]
Hi I think you are still using an example task as the first example here? If not please clarify - it doesn't seem like the same task as Example 2. Thanks!

**Comment by bigattichouse** [comment]
I was showing that the thought process was similar, I'll remove example #1

**Comment by bigattichouse** [comment]
Ok, removed confusing first task

**Comment by bigattichouse** [comment]
Updated the PR, should be good to go (unless I missed something else)

**Comment by teknium1** [comment]
Merging!

**Comment by bigattichouse** [comment]
Yay! Thank you for including my PR.

**Pull request merged**
