### PR TITLE
Add Synthetic Tasks

### PR DESCRIPTION
**Pull request by N8python**
Adds a sampling of synthetically generated tasks using a consensus-based LLM method (as described in the README, source code sent on discord, will be open-sourced soon). These tasks are generally easy, but are quite extensive, well formatted, and well written - as they are authored by Claude 3.5 Sonnet.

Judge models utilized: 

Llama 3.1 405B
GPT-4o
Claude 3.5 Sonnet
Qwen2 72B Instruct
WizardLM 2 8x22B

### CODE REVIEW

**Comment by N8python** [comment]
This is the code that generates the substance of the tasks from the list of task names: https://gist.github.com/N8python/d368dab9f09b253be43f7d4c00d18c44

The task names themselves are generated through prompting LLMs manually, or simply writing them out. No need to automate that.

**Comment by N8python** [comment]
Ready for review, I believe!

**Comment by N8python** [comment]
Extra ready now lol.

**Review by mmhamdy — COMMENTED** [review]
Cool! many interesting tasks in there!

**Comment by N8python** [comment]
Glad you like it :D!

**Pull request merged**
